name: models
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  freezed: ^3.2.3

flutter:
