name: domain
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none
environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  models:
    path: ../models
  injectable: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6

flutter:
