name: ui
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  models:
    path: ../../models
  domain:
    path: ../../domain
  rxdart: ^0.28.0
  injectable: ^2.3.2
  get_it: ^8.2.0
  go_router: ^16.2.5
  searchable_listview: ^2.15.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_hooks:
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3
  lottie: ^3.3.2
  google_fonts: ^6.2.1
  animate_do: ^4.2.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  path: ^1.9.1
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.2.3
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.4.0
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
