# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  flutter_unit_test:
    name: Test KRIS
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout branches
        uses: actions/checkout@v3

      - name: flutter analyze
        run: flutter analyze --fatal-warnings

      - name: flutter test
        run: flutter test

      - name: flutter build
        run: flutter build apk --release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: test_apk
          path: build/app/outputs/flutter-apk/app-release.apk
